(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const app=$('#app'),film=$('#film'),scenes=$$('.scene'),start=$('#start'),replay=$('#replay'),mute=$('#mute'),bar=$('#progressBar'),resume=$('#resume'),resumeBtn=$('#resumeBtn'),winterAudio=$('#winterAudio'),loveAudio=$('#loveAudio');
const durations=scenes.map(s=>Number(s.dataset.d||10));
const offsets=[];let sum=0;durations.forEach(d=>{offsets.push(sum);sum+=d});const total=sum;
let state='gate',current=-1,elapsed=0,last=0,raf=0,paused=false,waiting=false,muted=false;
const fired=new Set();

class Soundscape{constructor(){this.ctx=null;this.master=null;this.noise=null;this.bed=null}async init(){if(this.ctx){if(this.ctx.state==='suspended')await this.ctx.resume();return}const A=window.AudioContext||window.webkitAudioContext;if(!A)return;this.ctx=new A();this.master=this.ctx.createGain();this.master.gain.value=.25;this.master.connect(this.ctx.destination);this.noise=this.makeNoise(2.5);if(this.ctx.state==='suspended')await this.ctx.resume()}makeNoise(sec){const n=Math.floor(this.ctx.sampleRate*sec),b=this.ctx.createBuffer(1,n,this.ctx.sampleRate),a=b.getChannelData(0);let last=0;for(let i=0;i<n;i++){const w=Math.random()*2-1;last=last*.985+w*.015;a[i]=last*3.2}return b}setMute(v){if(!this.master||!this.ctx)return;this.master.gain.setTargetAtTime(v?0:.25,this.ctx.currentTime,.04)}stop(){if(!this.bed)return;try{this.bed.stop()}catch{}this.bed=null}ambient(cut=500,g=.04){if(!this.ctx||!this.noise)return;this.stop();const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),v=this.ctx.createGain();s.buffer=this.noise;s.loop=true;f.type='lowpass';f.frequency.value=cut;v.gain.value=g;s.connect(f).connect(v).connect(this.master);s.start();this.bed=s}tone(freq=660,len=.12,g=.06,type='sine',delay=0){if(!this.ctx||muted)return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),v=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);v.gain.setValueAtTime(.0001,t);v.gain.exponentialRampToValueAtTime(g,t+.015);v.gain.exponentialRampToValueAtTime(.0001,t+len);o.connect(v).connect(this.master);o.start(t);o.stop(t+len+.03)}chime(){this.tone(880,.16,.04,'sine');this.tone(1320,.18,.025,'sine',.045)}thump(){if(!this.ctx||muted)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),v=this.ctx.createGain();o.frequency.setValueAtTime(120,t);o.frequency.exponentialRampToValueAtTime(48,t+.18);v.gain.setValueAtTime(.17,t);v.gain.exponentialRampToValueAtTime(.0001,t+.2);o.connect(v).connect(this.master);o.start(t);o.stop(t+.22)}motif(){[440,523.25,659.25,587.33].forEach((f,i)=>this.tone(f,.8,.024,'sine',i*.55))}}
const sound=new Soundscape();

function once(key,globalAt,fn){if(fired.has(key)||elapsed<globalAt)return;fired.add(key);fn()}
function restart(scene){if(!scene)return;scene.classList.remove('active','leaving');void scene.offsetWidth}
function setScene(i,force=false){if(!force&&i===current)return;const prev=current;if(prev>=0&&scenes[prev]){scenes[prev].classList.remove('active');scenes[prev].classList.add('leaving');setTimeout(()=>scenes[prev]?.classList.remove('leaving'),700)}current=Math.max(0,Math.min(i,scenes.length-1));restart(scenes[current]);requestAnimationFrame(()=>scenes[current].classList.add('active'));sceneSound(scenes[current].dataset.name);updateDebug()}
function sceneSound(name){if(name!=='winter')winterAudio.pause();if(name!=='love')loveAudio.pause();if(!sound.ctx)return;sound.stop();const map={opening:[300,.03],road:[520,.085],montage:[380,.035],armor:[220,.025],winter:[900,.018],love:[170,.022],pressure:[540,.038],future:[260,.023],bedtime:[200,.018]};const p=map[name]||[300,.02];sound.ambient(p[0],p[1])}
function sceneAt(t){for(let i=scenes.length-1;i>=0;i--)if(t>=offsets[i])return i;return 0}
function orchestrate(i){const name=scenes[i].dataset.name,base=offsets[i],k=x=>name+':'+x;if(name==='opening'){once(k('a'),base+.5,()=>sound.chime());once(k('b'),base+1.7,()=>sound.chime())}if(name==='road'){once(k('call'),base+1.1,()=>sound.chime());once(k('shout'),base+7,()=>sound.thump())}if(name==='winter'){once(k('music'),base+3.5,()=>{if(winterAudio.readyState>=2){winterAudio.currentTime=0;winterAudio.volume=muted?0:.45;winterAudio.play().catch(()=>sound.motif())}else sound.motif()})}if(name==='love'){once(k('note'),base+2,()=>sound.chime());once(k('love'),base+6.8,()=>{if(loveAudio.readyState>=2){loveAudio.currentTime=0;loveAudio.volume=muted?0:.75;loveAudio.play().catch(()=>sound.tone(392,1,.022))}else sound.tone(392,1,.022)})}if(name==='bedtime'){once(k('night'),base+.8,()=>sound.chime());once(k('reply'),base+10.6,()=>sound.chime())}}
function tick(now){if(state!=='film')return;if(!last)last=now;if(!paused)elapsed+=(now-last)/1000;last=now;if(elapsed>=total){finish();return}const i=sceneAt(elapsed);setScene(i);bar.style.width=Math.min(100,elapsed/total*100)+'%';orchestrate(i);updateDebug();raf=requestAnimationFrame(tick)}
async function begin(){state='film';app.dataset.state='film';film.setAttribute('aria-hidden','false');$('#epilogue').setAttribute('aria-hidden','true');elapsed=0;last=0;current=-1;paused=false;waiting=false;fired.clear();bar.style.width='0';scenes.forEach(restart);winterAudio.pause();loveAudio.pause();winterAudio.currentTime=0;loveAudio.currentTime=0;try{await sound.init()}catch{}sound.setMute(muted);setScene(0,true);cancelAnimationFrame(raf);raf=requestAnimationFrame(tick)}
function finish(){cancelAnimationFrame(raf);sound.stop();winterAudio.pause();loveAudio.pause();state='epilogue';app.dataset.state='epilogue';film.setAttribute('aria-hidden','true');$('#epilogue').setAttribute('aria-hidden','false')}
function toggleMute(){muted=!muted;sound.setMute(muted);winterAudio.muted=muted;loveAudio.muted=muted;mute.textContent=muted?'×':'◖';mute.setAttribute('aria-label',muted?'Включить звук':'Выключить звук')}
function interrupt(){if(state!=='film'||paused)return;paused=true;waiting=true;sound.ctx?.suspend().catch(()=>{});winterAudio.pause();loveAudio.pause()}
function showResume(){if(waiting&&state==='film')resume.classList.add('show')}
async function continueFilm(){waiting=false;paused=false;last=performance.now();resume.classList.remove('show');if(sound.ctx?.state==='suspended')await sound.ctx.resume().catch(()=>{});const name=scenes[current]?.dataset.name;sceneSound(name);if(name==='winter'&&winterAudio.readyState>=2&&winterAudio.currentTime>0)winterAudio.play().catch(()=>{});if(name==='love'&&loveAudio.readyState>=2&&loveAudio.currentTime>0)loveAudio.play().catch(()=>{})}

const debugMode=new URLSearchParams(location.search).get('debug')==='1',debug=$('#debug'),debugScene=$('#debugScene'),debugTime=$('#debugTime');
function updateDebug(){if(!debugMode)return;debugScene.textContent=current>=0?`${current+1}/${scenes.length} ${scenes[current].dataset.name}`:'—';debugTime.textContent=`${elapsed.toFixed(1)} / ${total}s`}
function seek(delta){if(state!=='film')return;const t=Math.max(0,Math.min(scenes.length-1,current+delta));elapsed=offsets[t]+.05;last=performance.now();fired.clear();winterAudio.pause();loveAudio.pause();setScene(t,true)}
if(debugMode){debug.hidden=false;$('#prev').addEventListener('click',()=>seek(-1));$('#next').addEventListener('click',()=>seek(1))}

start.addEventListener('click',begin);replay.addEventListener('click',begin);mute.addEventListener('click',toggleMute);resumeBtn.addEventListener('click',continueFilm);
document.addEventListener('visibilitychange',()=>{if(document.hidden)interrupt();else showResume()});window.addEventListener('pagehide',interrupt);
})();
